### ISSUE TITLE
r3d3 Review - Grid Representation

### ISSUE THREAD

**Issue by kkysen** [sngo1/whySoCereal#5]
A grid of all the cereals seems kind of boring and unappealing.  Maybe another view or representation would be better.  Perhaps one that relates some attribute of each cereal, something more like the bubble chart.  However, for the bubble chart, I'm not sure how the cereals are arranged.  Does their size depend on how much of nutrient is in that cereal, or something else?

**Comment by sngo1** [comment]
We will figure that out, thank you for your input.
