### ISSUE TITLE
r3d3 Review - Limited Data

### ISSUE THREAD

**Issue by kkysen** [sngo1/whySoCereal#6]
The cereal data seems pretty limited, and applying your ideas to other foods shouldn't be that much harder--most of the same analyses and code probably can be used--so maybe you can extend this project to other foods as well.

Also, what kind of cereal name is smacks?

**Comment by sngo1** [comment]
![](https://images-na.ssl-images-amazon.com/images/I/91qUq96pbjL._SY355_.jpg)
